postgresql:
  database: otus
  username: user
  password: password
  image: postgres:15.7
  service:
    type: NodePort
    port: 5432
    nodePort: 30002
  persistence:
    enabled: true
    size: 1Gi